spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/system_mgmt
    username: root
    password: itsmpass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080
  max-http-request-header-size: 64KB

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name:itsm-system}
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.itsm.system.service.auth: TRACE
    com.itsm.system.security: TRACE

jwt:
  secret: ${JWT_SECRET:ITSMLongSecretKeyForSecurityPurposes1234567890!}
  expiration: 86400000
