apiVersion: 1

datasources:
  - name: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    isDefault: true
    editable: true
  # 1. Prometheus 설정
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: false
    jsonData:
      httpMethod: POST
      # Prometheus와 Tempo를 연결하는 설정 (Trace ID 클릭 시 이동)
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
  - name: loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"trace_id":"(\w+)"'
          name: TraceID
          url: '$${__value.raw}'